#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/eventy
#    username: eventy
#    password: eventy
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
  http:
    multipart:
      max-file-size: 10MB
logging:
  level: INFO


custom:
  image.repo: "C:\\Users\\david\\Pictures\\eventy"