#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/eventy
#    username: eventy
#    password: eventy
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
custom:
  image.repo: "C:\\Users\\david\\Pictures\\eventy"
  eventy.ui: "C:\\dev\\workspace\\eventy-ui\\" # last backslash is important!
  dump.location: "C:\\dev\\workspace\\eventy\\dumps"

spring:
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      #cluster-nodes: 138.68.133.117:9300
  http:
    multipart:
      max-file-size: 10MB
#logging:
#  level: INFO

server:
  port: 8080
  address: 0.0.0.0

endpoints:
  shutdown:
    enabled: true
  actuator:
    enabled: true
management:
  security:
    enabled: false
